1. Write a function so that the columns of the output matrix are powers of the input vector.
1. The order of the powers is determined by the increasing boolean argument. Specifically, when
   increasing is False, the i-th output column is the input vector raised element-wise to the power
   of N - i - 1.

In [1]:
# we we will use np.vander()
import numpy as np
x = np.array([1,2,3,4,5])
y = 5
result = np.vander(x, y, increasing = False)
print(result)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [2]:
#to find the determinant of the matrix
np.linalg.det(result)

287.9999999999977

In [3]:
# 2 method
import numpy as np
x = np.array([1,2,3,4,5])
y = 5
result1 = np.column_stack([x**(N-i-1)])

NameError: name 'matrix' is not defined